#Configuraciones globales actualizadas dinamicamente
#Sat May 30 11:49:50 ART 2026
principal.puerto=5000
respaldo.ip=localhost
seguridad.algoritmo=Vigenere
respaldo.puerto=5010
seguridad.clave=ABC
intervaloPing=200
principal.ip=localhost
maxIntentosFallidos=3
persistencia.archivo=historial_filas
persistencia.formato=JSON
