#Configuraciones globales actualizadas dinamicamente
#Fri Jun 05 17:42:21 ART 2026
principal.puerto=5000
respaldo.ip=localhost
seguridad.algoritmo=Vigenere
respaldo.puerto=5010
seguridad.clave=ABC
intervaloPing=200
principal.ip=localhost
maxIntentosFallidos=3
persistencia.archivo=archivo_de_guardado
persistencia.formato=TXT
